[versions]
kotlin = '1.5.21'
compose = '1.0.1'
retrofit = '2.9.0'
room = '2.3.0'
coroutines = '1.5.2'
lifecycle = '2.2.0'

[libraries]
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
core = 'androidx.core:core-ktx:1.7.0'
appcompat = 'androidx.appcompat:appcompat:1.3.1'
material = 'com.google.android.material:material:1.4.0'
compose-ui-ui = { module = 'androidx.compose.ui:ui', version.ref = 'compose' }
compose-material = { module = 'androidx.compose.material:material', version.ref = 'compose' }
compose-ui-preview = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = 'compose' }
compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'compose' }
activity-compose = 'androidx.activity:activity-compose:1.3.0-alpha06'
retrofit-retrofit = { module = 'com.squareup.retrofit2:retrofit', version.ref = 'retrofit' }
retrofit-moshi = { module = 'com.squareup.retrofit2:converter-moshi', version.ref = 'retrofit' }
moshi-adapter = 'com.squareup.moshi:moshi-adapters:1.8.0'
room-runtime = { module = 'androidx.room:room-runtime', version.ref = 'room' }
room-ktx = { module = 'androidx.room:room-ktx', version.ref = 'room' }
room-compiler = { module = 'androidx.room:room-compiler', version.ref = 'room' }
lifecycle-viewmodel-ktx = { module = 'androidx.lifecycle:lifecycle-viewmodel-ktx', version.ref = 'lifecycle' }
lifecycle-viewmodel-compose = { module = 'androidx.lifecycle:lifecycle-viewmodel-compose', version.ref = 'lifecycle' }
lifecycle-livedata-ktx = { module = 'androidx.lifecycle:lifecycle-livedata-ktx', version.ref = 'lifecycle' }
junit = 'junit:junit:4.13.2'
mockk = 'io.mockk:mockk:1.12.0'
kotest = 'io.kotlintest:kotlintest-runner-junit5:3.4.2'
robolectric = 'org.robolectric:robolectric:4.5.1'
test-core = 'androidx.test:core:1.4.0'
