[versions]
kotlin = '1.5.21'
compose = '1.0.1'
retrofit = '2.9.0'

[libraries]
core = 'androidx.core:core-ktx:1.7.0'
appcompat = 'androidx.appcompat:appcompat:1.3.1'
material = 'com.google.android.material:material:1.4.0'
compose-ui-ui = { module = 'androidx.compose.ui:ui', version.ref = 'compose' }
compose-material = { module = 'androidx.compose.material:material', version.ref = 'compose' }
compose-ui-preview = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = 'compose' }
compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'compose' }
activity-compose = 'androidx.activity:activity-compose:1.3.0-alpha06'
retrofit-retrofit = { module = 'com.squareup.retrofit2:retrofit', version.ref = 'retrofit' }
retrofit-moshi =  { module = 'com.squareup.retrofit2:converter-moshi', version.ref = 'retrofit' }
moshi-adapter = 'com.squareup.moshi:moshi-adapters:1.8.0'
junit = 'junit:junit:4.13.2'
kotest = 'io.kotlintest:kotlintest-runner-junit5:3.4.2'
