name: check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: gradle/gradle-build-action@v2
      - run: cp gradle.properties.ci gradle.properties
      - run: ./gradlew spotlessCheck
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew koverHtmlReportDebug
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: app/build/reports/kover/htmlDebug/
      # Dependency Tree Diff
      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        if: github.event_name == 'pull_request'
      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff
        if: github.event_name == 'pull_request'
      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event_name == 'pull_request' && (steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null) }}
        with:
          body: |
            Dependency diff (customize your message here):
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # Slack
      - uses: tfandkusu/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
