name: check
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - uses: gradle/gradle-build-action@v2
      - run: cp gradle.properties.ci gradle.properties
      - run: ./gradlew spotlessCheck
      - run: bundle exec danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew jacocoTestReport
      # Codecov
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov -t ${{ secrets.CODECOV_TOKEN }}
      # Dependency Tree Diff
      - id: dependency-diff
        name: Generate dependency diff
        uses: usefulness/dependency-tree-diff-action@v1
        if: github.event_name == 'pull_request'
      - uses: peter-evans/find-comment@v2
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Dependency diff
        if: github.event_name == 'pull_request'
      - uses: peter-evans/create-or-update-comment@v2
        if: ${{ github.event_name == 'pull_request' && (steps.dependency-diff.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null) }}
        with:
          body: |
            Dependency diff (customize your message here):
              ```diff
              ${{ steps.dependency-diff.outputs.text-diff }}
              ```
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # Slack
      - uses: tfandkusu/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: always()
  androidTest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout
      - uses: actions/checkout@v3
      # Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      # Gradle
      - uses: gradle/gradle-build-action@v2
      # Build
      - run: ./gradlew app:assembleDebug data:local:assembleDebugAndroidTest
      # gcloud command
      # https://github.com/google-github-actions/setup-gcloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # Firebase Test Lab
      - run: gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test data/local/build/outputs/apk/androidTest/debug/local-debug-androidTest.apk --device model=MediumPhone.arm,version=33 --environment-variables coverage=true,coverageFile="/sdcard/Download/coverage.ec" --directories-to-pull /sdcard/Download 2>&1 | tee result.txt
